// app/components/Header.tsx
import Link from 'next/link'

export default function Header() {
    return (
        <div className="container mx-auto mt-4">
            <div className="flex justify-center">
                <ul className="menu menu-horizontal space-x-0.5 rtl:space-x-reverse">
                    <li>
                        <Link href="/">
                            <span className="icon-[tabler--home] size-5"></span>Home
                        </Link>
                    </li>
                    <li>
                        <Link href="/career">
                            <span className="icon-[tabler--device-desktop-analytics] size-5"></span>Career
                        </Link>
                    </li>
                    <li>
                        <Link href="/travel">
                            <span className="icon-[tabler--globe-filled] size-5"></span>Travel
                        </Link>
                    </li>
                    <li>
                        <Link href="/photos">
                            <span className="icon-[tabler--camera] size-5"></span>Photos
                        </Link>
                    </li>
                    <li>
                        <Link href="/contact">
                            <span className="icon-[tabler--phone-call] size-5"></span>Contact
                        </Link>
                    </li>
                </ul>
            </div>
        </div>
    );
  }

// src/components/Header.vue
<template>
  <div class="container mx-auto mt-4">
    <div class="flex justify-center">
      <ul class="menu sm:menu-horizontal">
        <li>
          <RouterLink to="/">
            <span class="icon-[tabler--home] size-5"></span>
            Home
          </RouterLink>
        </li>
        <li>
          <RouterLink to="/career">
            <span class="icon-[tabler--device-desktop-analytics] size-5"></span>
            Career
          </RouterLink>
        </li>
        <li>
          <RouterLink to="/travel">
            <span class="icon-[tabler--globe-filled] size-5"></span>
            Travel
          </RouterLink>
        </li>
        <li>
          <RouterLink to="/photos">
            <span class="icon-[tabler--camera] size-5"></span>
            Photos
          </RouterLink>
        </li>
        <li>
          <RouterLink to="/contact">
            <span class="icon-[tabler--phone-call] size-5"></span>
            Contact
          </RouterLink>
        </li>
      </ul>
    </div>
  </div>
</template>
