// app/components/Resume.tsx
export default function Resume() {
    return (
        <div className="flex items-center flex-col justify-center mt-11">
            <button className="btn btn-gradient btn-primary"><span className="icon-[tabler--download]"></span>Download My Resume</button>
            <span className="mt-2 text-sm"><em>Or check the <u><a href="">Career</a></u> page.</em></span>
        </div>
    );
  }

// src/components/Resume.vue
<template>
    <div class="flex items-center flex-col justify-center mt-11">
        <button class="btn btn-gradient btn-primary"><span class="icon-[tabler--download]"></span>Download My Resume</button>
        <span class="mt-2 text-sm"><em>Or check the <u><a href="">Career</a></u> page.</em></span>
    </div>
</template>
